all:
  hosts:
    Project_1:
      ansible_host: 192.168.155.190
      ansible_user: root
      ansible_password: toortoor
    Project_2:
      ansible_host: 192.168.155.250
      ansible_user: root
      ansible_password: toortoor
    Project_3:
      ansible_host: 192.168.155.249
      ansible_user: root
      ansible_password: toortoor
  
