---
- hosts: all
  name: WSR playbook
  vars:
    users:
    -  Webdeveloper
    -  Devopsengineer
    -  Projectmanager
    passwords: 
    - S52we9V6QTp7
    - dHy6sKGHsj2T
    - oP92ugMSaCbe
    publickey:
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM=
  vars_files:
  - /wsr-skillcloud/Users/privvars.yml
  tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: install curl
      apt:
         pkg: curl
         state: latest
    - name: activate ufw
      ufw:
        state: enabled 
    - name: allow ports TCP 80,8080,1834
      ufw:
        rule: allow
        port: 80,8080,1834
        proto: tcp
    - name: change ssh port in sshd_config
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^Port'
        line: "Port 1834"
    - name: allow ssh public key authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: 'PubkeyAuthentication no'
        line: "PubkeyAuthentication yes"
    - name: create users
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        home: "/home/{{ item.name }}/"
        password: "{{ item.pass }}"
        ssh_key_file: .ssh/id_rsa
      loop:
      - { name: 'Webdeveloper', pass: 'S52we9V6QTp7' }
      - { name: 'Devopsengineer', pass: 'dHy6sKGHsj2T' }
      - { name: 'Projectmanager', pass: 'oP92ugMSaCbe' }
    - name: create .ssh
      file:
        path: "/home/{{item.name}}/.ssh/"
        state: directory
      loop:
      - { name: 'Webdeveloper' }
      - { name: 'Devopsengineer' }
      - { name: 'Projectmanager' } 
    - name: create authorized_keys file
      file:
        path: "/home/{{item.name}}/.ssh/authorized_keys" 
        state: touch
      loop:
      - { name: 'Webdeveloper' }
      - { name: 'Devopsengineer' }
      - { name: 'Projectmanager' } 
    - name: add public keys to users
      lineinfile:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
        line: "{{ publickey }}"
      loop:
      - { name: 'Webdeveloper' }
      - { name: 'Devopsengineer' }
      - { name: 'Projectmanager' } 
    - name: install docker
      apt:
        pkg: docker.io
    - name: create directory /skillcloud-nginx 
      file:
        path: /skillcloud-nginx
        state: directory
    - name: copy necessary files
      copy:
        src: "{{ item }}"
        dest: /skillcloud-nginx/
      with_fileglob:
      - /wsr-skillcloud/D*
      - /wsr-skillcloud/nginx.conf
      - /wsr-skillcloud/index.html
    - name: execute docker-compose.sh file
      script: /wsr-skillcloud/docker-compose.sh
    - name: reload ssh and ufw
      service:
        name: ssh
        state: restarted
    - name: restart sshd
      service:
        name: sshd
        state: restarted
    - name: restart ufw
      service:  
        name: ufw
        state: restarted
    - name: reboot
      reboot:      
